### ISSUE TITLE
Implementing the fix imports function from the import-js project

### ISSUE THREAD

**Issue by ivangeorgiew** [kristijanhusak/vim-js-file-import#7]
Hi, is it possible to implement the functionality "fix imports" from the other project here?
I went through your code and am not sure if it will be possible without major refactoring.
I like the idea of your repo, but that is the only functionality that I use from the other one.

**Comment by kristijanhusak** [comment]
What exactly fix imports should do?

**Comment by ivangeorgiew** [comment]
It searches your whole file for missing imports and adds them or removes unused ones. This way you can write your file and at the end fix the imports. And if you have changed the some file names of the imports or the locations, you can just delete the old ones and import the new ones with one command.

**Comment by kristijanhusak** [comment]
I don't think this would require refactoring, but definetely a lot of coding. Also i'm not sure if it would be available without some AST, like import-js does it.

One problem that i see with this is that some things can be imported from multiple places. What should it do then, ask?

**Comment by ivangeorgiew** [comment]
Hmm, I was seeing it like this:
1) remove unused imports
2) search for the locally undefined variables in the file and add them to a list
3) search the tags for each item in that list
  - if there is none, do nothing
  - if there is one use it
  - if there are multiple show the user, the options
4) append the imports
5) sort the imports

Obviously, step 2 is the most difficult one. If you manage to implement it somehow, the rest should be easy.
A suggestion - https://github.com/w0rp/ale already shows all the undefined variables in a file. Maybe you can see how it is done there and implement it here as well or use it in some other way.

**Comment by kristijanhusak** [comment]
Yeah something like that would work, but few things are still not that easy:

1. I already have simple implementation of removing unused imports, but doesn't work on partial imports.
2. This adds an eslint dependency to the plugin.
3,4,5: Sounds ok.

I'll give it a try when i get some time, currently preparing for vacation, so i can't do much for another 2-3 weeks.

**Comment by ivangeorgiew** [comment]
1. you can use eslint for that as well
2. the complication of adding this dependency is the same as adding UniversalTags

**Comment by kristijanhusak** [comment]
I created initial version, it's on the `feature/fix-imports` branch. I tested it only with es5 (require). One thing that is currently missing is removing unused imports that span on multiple lines.

```js
const {
  get
} = require('lodash')
```

Eslint returns only `get` as invalid instead of whole import. I'll fix that eventually.

Also, i'm pretty much assuming that Eslint is set up on the project. Haven't tested without the setup.

**Comment by kristijanhusak** [comment]
@ivangeorgiew i wrapped it up. It should properly handle both es5 and es6 imports, and properly clean even multiline imports like in example above.

Please give it a test, and if it works, i'll put it to master.

**Comment by ivangeorgiew** [comment]
`Error detected while processing function jsfileimport#fix_imports#exec[44]..jsfileimport#utils#_restore_cursor_position:`
`E20: Mark not set`

This was the initial error which I fixed by changin `normal` to `normal!`
But then I received this error which I can't fix, since I don't know where it occurs:
`Vim(let):E730: using List as a String`

**Comment by kristijanhusak** [comment]
I cannot reproduce the second error. Can you provide me:
1. List of imports that you are trying to fix. If possible, whole js file.
2. Eslint version
3. Are you using local installation `./node_modules/.bin/eslint` or global?
4. Eslint config

**Comment by ivangeorgiew** [comment]
I just found out that this project doesn't import from `node_modules`.
Even if the fix imports command was working, the need for manually adding imports from `node_modules` renders it obsolete.
If you are not planning to add that functionality, I am sorry that I asked you to add the fix imports command.

**Comment by kristijanhusak** [comment]
But it does know to import from your package.json. If you have a `lodash` dependency, trying import on `lodash` will import that.
I'll wrap this up anyway because it's good feature.

**Comment by ivangeorgiew** [comment]
Oh sorry, I was wrong then.

**Comment by ivangeorgiew** [comment]
The pathing for eslint may be incorrect like in my case, but even if I use the correct pathing, I receive the following error: `Vim(let):E730: using List as a String`

**Comment by kristijanhusak** [comment]
@ivangeorgiew I fixed eslint path issue.
Can you give me the list of imports that you are using? Is it `import` or `require` ?

**Comment by ivangeorgiew** [comment]
It is import. I forgot you mentioned, you made it work with require only right?

**Comment by kristijanhusak** [comment]
No, it should work with both. I tested with both, works fine for me on linux. What os are you using?

**Comment by kristijanhusak** [comment]
Please test first with this:
```jsx
import React from 'react';
import ShouldBeRemoved, { Field } from 'redux-form';
import Select from './fields/Select';
import ThisAlsoShouldBeRemoved from './fields/Removed';
import { getData, NotNeeded } from './somewhere';

const MyComponent = () => {
  const data = getData();
  return (
    <form>
      <Field name="test" component="input" />
      <Select />
    </form>
  );
};

export default MyComponent;
```

This is only for removing unused ones.
If you can, test with your eslint in the project, and no eslint config. Just make sure to do npm install in plugin directory before trying the second.

**Comment by ivangeorgiew** [comment]
Nope still doesn't work. I even created a new folder, ran npm init in it, installed eslint locally. Still doesn't work. with the file you have provided. The error is the same.

**Comment by kristijanhusak** [comment]
Does manual importing work for you? does `:echo has('python3')` return `1`?
I tried running neovim with verbose log like explained here https://stackoverflow.com/a/3026029/1474465, and then i started getting that same error, and my deoplete failed immediately because python3 doesn't exist in that case.

**Comment by ivangeorgiew** [comment]
Yes, I do. Why don't you add me on skype? It will be a lot faster than typing over 9000 comments.

**Comment by kristijanhusak** [comment]
Added you.
